package com.bifrost.poc.messages;// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PreferredNotificationChannel extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static PreferredNotificationChannel getRootAsPreferredNotificationChannel(ByteBuffer _bb) { return getRootAsPreferredNotificationChannel(_bb, new PreferredNotificationChannel()); }
  public static PreferredNotificationChannel getRootAsPreferredNotificationChannel(ByteBuffer _bb, PreferredNotificationChannel obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PreferredNotificationChannel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String channel() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer channelAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer channelInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String preselectedPhone() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer preselectedPhoneAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer preselectedPhoneInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createPreferredNotificationChannel(FlatBufferBuilder builder,
      int channelOffset,
      int preselectedPhoneOffset) {
    builder.startTable(2);
    PreferredNotificationChannel.addPreselectedPhone(builder, preselectedPhoneOffset);
    PreferredNotificationChannel.addChannel(builder, channelOffset);
    return PreferredNotificationChannel.endPreferredNotificationChannel(builder);
  }

  public static void startPreferredNotificationChannel(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addChannel(FlatBufferBuilder builder, int channelOffset) { builder.addOffset(0, channelOffset, 0); }
  public static void addPreselectedPhone(FlatBufferBuilder builder, int preselectedPhoneOffset) { builder.addOffset(1, preselectedPhoneOffset, 0); }
  public static int endPreferredNotificationChannel(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PreferredNotificationChannel get(int j) { return get(new PreferredNotificationChannel(), j); }
    public PreferredNotificationChannel get(PreferredNotificationChannel obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

